# Generated by Django 4.2.2 on 2023-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('rate_vkurse', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('rate_nbu', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('rate_minfin', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
